FROM fedora:41
RUN dnf install -y ca-certificates sudo rpm-build bindfs
RUN <<EOF
    useradd -m -s /bin/bash -G wheel user
    echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/user
    chmod 0440 /etc/sudoers.d/user

    useradd -m -s /bin/bash alr
    mkdir -p /var/cache/alr /etc/alr
    chown alr:alr /var/cache/alr /etc/alr
EOF
COPY ./alr /usr/bin
RUN <<EOF
    setcap cap_setuid,cap_setgid+ep /usr/bin/alr
EOF
USER user
WORKDIR /home/user
ENTRYPOINT ["tail", "-f", "/dev/null"]