FROM ubuntu:24.10
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates sudo libcap2-bin
RUN <<EOF
    useradd -m -s /bin/bash user
    echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/user
    chmod 0440 /etc/sudoers.d/user 
    
    useradd -m -s /bin/bash alr
    mkdir -p /var/cache/alr /etc/alr
    chown alr:alr /var/cache/alr /etc/alr
EOF
COPY ./alr /usr/bin
RUN <<EOF
    setcap cap_setuid,cap_setgid+ep /usr/bin/alr
EOF
USER user
ENTRYPOINT ["tail", "-f", "/dev/null"]